// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class new_collectionadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_collectionadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202410061139476_new_collection-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
